### ISSUE TITLE
Shape structure not in line with spec: continuous_dropoff vs continuous_drop_off

### ISSUE THREAD

**Issue by vesavlad** [InspectorIncognito/gtfs-editor-backend#10]
Please see https://gtfs.org/schedule/reference/#stop_timestxt

**Comment by felipinbombin** [comment]
Hi @vesavlad, thanks to reach out. You are right, we already have fixed the problem. 👍🏻 

commit: https://github.com/InspectorIncognito/gtfs-editor-backend/commit/4939f61d27587ee2e7829706ff34434241fdf3da
